targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: library_store|lib/graphql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: library_store|lib/graphql/schema.graphql
          custom_serializers:
            - import: "package:built_value/iso_8601_date_time_serializer.dart"
              name: Iso8601DateTimeSerializer
          when_extensions:
            when: true
            maybeWhen: true
